export const SET_PRODUCTS = "SET_PRODUCTS";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const INIT_STATUS = "INIT_STATUS";
export const SET_STATUS_LOADING = "SET_STATUS_LOADING";
